version: "3.4"
services:
  identity:
    image: codeit/identity:dev
    container_name: identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "7580:80"
      #- "7543:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      #- ./infrastructure/identity/Codeit.Infrastructure.Identity/tempkey.jwk:/etc/ssl/certs/tempkey.jwk
  #  depends_on:
  #    - sqldb

  #sqldb:
  #  image: mcr.microsoft.com/mssql/server:2019-latest
  #  container_name: sqldb
  #  restart: always
  #  environment:
  #    SA_PASSWORD: "Devadmin321"
  #    ACCEPT_EULA: "Y"
  #  ports:
  #    - "5433:1433"
  #  volumes:
  #    - sqldb-data:/var/opt/mssql

volumes:
  sqldb-data: